In [5]:
import pandas as pd
from sklearn.datasets import load_iris
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score
from sklearn.model_selection import train_test_split

In [6]:
data = load_iris()
df_iris = pd.DataFrame(data.data, columns = ['sepal length', 'sepal width', 'petal length', 'petal width'])
df_iris['class'] = data.target
df_iris.head()

sepal length  sepal width  petal length  petal width  class
0           5.1          3.5           1.4          0.2      0
1           4.9          3.0           1.4          0.2      0
2           4.7          3.2           1.3          0.2      0
3           4.6          3.1           1.5          0.2      0
4           5.0          3.6           1.4          0.2      0

In [7]:
iris_model = LogisticRegression(solver='liblinear', multi_class='ovr')
iris_model.fit(df_iris.values, df_iris['class'])

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='ovr',
          n_jobs=None, penalty='l2', random_state=None, solver='liblinear',
          tol=0.0001, verbose=0, warm_start=False)

In [8]:
iris_pred = iris_model.predict(df_iris.values)
accuracy_score(iris_pred, df_iris['class'])

1.0

In [9]:
X = df_iris.drop('class', axis=1).values
Y = df_iris['class'].values
x_train, x_test, y_train, y_test = train_test_split(X, Y, test_size=0.3, random_state=100)

In [10]:
iris_model = LogisticRegression(solver='liblinear', multi_class='ovr')
iris_model.fit(x_train, y_train)
y_pred = iris_model.predict(x_test)
accuracy_score(y_pred, y_test)

1.0

In [11]:
from sklearn import svm

clf = svm.SVC(gamma='scale')
clf.fit(x_train, y_train)  
accuracy_score(clf.predict(x_test), y_test)

0.9777777777777777

In [8]:
from sklearn.neural_network import MLPClassifier

nn_clf = MLPClassifier(activation='relu', max_iter=500, hidden_layer_sizes=(20, 30))
nn_clf.fit(x_train, y_train)
nn_clf.predict(x_test)

/home/xma/anaconda3/lib/python3.7/site-packages/sklearn/neural_network/multilayer_perceptron.py:562: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)


array([2, 0, 2, 0, 2, 2, 0, 0, 2, 0, 0, 2, 0, 0, 2, 1, 1, 1, 2, 2, 2, 0,
       2, 0, 1, 2, 1, 0, 1, 2, 1, 1, 2, 0, 0, 1, 0, 1, 2, 2, 0, 1, 2, 2,
       0])

In [9]:
nn_clf.predict_proba(x_test)

array([[6.30044005e-06, 2.22701502e-03, 9.97766685e-01],
       [9.99364466e-01, 6.35524140e-04, 9.78940166e-09],
       [1.85398347e-07, 8.06127285e-05, 9.99919202e-01],
       [9.99921320e-01, 7.86799579e-05, 1.65924620e-10],
       [4.00022975e-04, 2.33131240e-01, 7.66468737e-01],
       [6.41288023e-06, 6.25311229e-03, 9.93740475e-01],
       [9.99917219e-01, 8.27809209e-05, 4.18789521e-10],
       [9.99221452e-01, 7.78532520e-04, 1.55648492e-08],
       [9.77898034e-05, 5.32090830e-02, 9.46693127e-01],
       [9.98890408e-01, 1.10956683e-03, 2.54733767e-08],
       [9.99733931e-01, 2.66065920e-04, 3.01390763e-09],
       [1.57273871e-05, 8.80815246e-03, 9.91176120e-01],
       [9.98907173e-01, 1.09281241e-03, 1.42937006e-08],
       [9.99700556e-01, 2.99441175e-04, 2.87607090e-09],
       [2.92597290e-05, 2.16474868e-02, 9.78323254e-01],
       [8.08122072e-04, 9.97063589e-01, 2.12828899e-03],
       [1.19050406e-03, 9.97410090e-01, 1.39940624e-03],
       [6.97125505e-04, 7.90902

In [10]:
accuracy_score(nn_clf.predict(x_test), y_test)

1.0

In [11]:
nn_clf.predict(x_test)

array([2, 0, 2, 0, 2, 2, 0, 0, 2, 0, 0, 2, 0, 0, 2, 1, 1, 1, 2, 2, 2, 0,
       2, 0, 1, 2, 1, 0, 1, 2, 1, 1, 2, 0, 0, 1, 0, 1, 2, 2, 0, 1, 2, 2,
       0])

In [3]:
import numpy as np
from sklearn.datasets import load_wine
from sklearn.preprocessing import MinMaxScaler, OneHotEncoder
from keras.layers import Dense, Input, concatenate, Dropout
from keras.models import Model
from keras.optimizers import rmsprop

dataset = load_wine()

ensemble_num = 10 # number of sub-networks
bootstrap_size = 0.8 # 80% size of original (training) dataset
training_size = 0.8 # 80% for training, 20% for test

num_hidden_neurons = 10 # number of neurons in hidden layer
dropout = 0.25 # percentage of weights dropped out before softmax output (this prevents overfitting)

epochs = 200 # number of epochs (complete training episodes over the training set) to run
batch = 10 # mini batch size for better convergence

# get the holdout training and test set
temp = []
scaler = MinMaxScaler()
one_hot = OneHotEncoder() # one hot encode the target classes
dataset['data'] = scaler.fit_transform(dataset['data'])
dataset['target'] = one_hot.fit_transform(np.reshape(dataset['target'], (-1,1)) ).toarray()
for i in range(len(dataset.data)):
    temp.append([dataset['data'][i], np.array(dataset['target'][i])])

# shuffle the row of data and targets
temp = np.array(temp)
np.random.shuffle(temp)
# holdout training and test stop index
stop = int(training_size*len(dataset.data))

train_X = np.array([x for x in temp[:stop,0]])
train_Y = np.array([x for x in temp[:stop,1]])
test_X = np.array([x for x in temp[stop:,0]])
test_Y = np.array([x for x in temp[stop:,1]])

# now build the ensemble neural network
# first, let's build the individual sub-networks, each
# as a Keras functional model.
sub_net_outputs = []
sub_net_inputs = []
for i in range(ensemble_num):
    # two hidden layers to keep it simple
    # specify input shape to the shape of the training set
    net_input = Input(shape = (train_X.shape[1],))
    sub_net_inputs.append(net_input)
    y = Dense(num_hidden_neurons)(net_input)
    y = Dense(num_hidden_neurons)(y)
    y = Dropout(dropout)(y)
    sub_net_outputs.append(y) # sub_nets contains the output tensors

# now concatenate the output tensors
y = concatenate(sub_net_outputs)

# final softmax output layer
y = Dense(train_Y[0].shape[0], activation='softmax')(y)

# now build the whole funtional model
model = Model(inputs=sub_net_inputs, outputs=y)
model.compile(optimizer='rmsprop', loss='categorical_crossentropy')

print("Begin training...")

# train the model
# model.fit( [train_X] * ensemble_num, train_Y,validation_data=[ [test_X] * ensemble_num, test_Y],
#           epochs=epochs, batch_size=batch)

/home/xma/anaconda3/lib/python3.7/site-packages/sklearn/preprocessing/_encoders.py:371: FutureWarning: The handling of integer data will change in version 0.22. Currently, the categories are determined based on the range [0, max(values)], while in the future they will be determined based on the unique values.
If you want the future behaviour and silence this warning, you can specify "categories='auto'".
In case you used a LabelEncoder before this OneHotEncoder to convert the categories to integers, then you can now use the OneHotEncoder directly.
  warnings.warn(msg, FutureWarning)


Begin training...
